package project

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/local-deploy/dl/utils"
	"github.com/pterm/pterm"
	"github.com/sirupsen/logrus"
)

// HostMapping describes the host to document root mapping declared in .env.
type HostMapping struct {
	Host         string
	DocumentRoot string
}

var hostMappings []HostMapping

type virtualHost struct {
	Primary      string
	Aliases      []string
	DocumentRoot string
	IsBitrix     bool
}

type nginxTemplateData struct {
	HostName string
	Servers  []virtualHost
}

func configureVirtualHosts() {
	hostMappings = parseHostMappings(Env.GetString("HOSTS_MAP"))
	Env.Set("TRAEFIK_EXTRA_RULE", buildTraefikRule(hostMappings))

	if err := ensureApacheConfig(); err != nil {
		pterm.FgRed.Printfln("failed to prepare apache config: %s", err)
		os.Exit(1)
	}

	if len(hostMappings) == 0 {
		return
	}

	if Env.InConfig("NGINX_CONF") {
		logrus.Warn("HOSTS_MAP is set but custom NGINX_CONF is used; skip autogenerated config")
		return
	}

	path, err := renderNginxConfig()
	if err != nil {
		pterm.FgRed.Printfln("failed to prepare nginx config: %s", err)
		os.Exit(1)
	}

	logrus.Infof("Using generated nginx config: %s", path)
	Env.Set("NGINX_CONF", path)
}

func ensureApacheConfig() error {
	if Env.InConfig("APACHE_CONF") && Env.GetString("APACHE_CONF") != "" {
		return nil
	}

	path, err := renderApacheConfig()
	if err != nil {
		return err
	}

	logrus.Infof("Using generated apache config: %s", path)
	Env.Set("APACHE_CONF", path)

	return nil
}

func renderNginxConfig() (string, error) {
	tpl, err := template.New("nginx").Funcs(template.FuncMap{"join": strings.Join}).Parse(nginxTemplate)
	if err != nil {
		return "", err
	}

	data := nginxTemplateData{
		HostName: Env.GetString("HOST_NAME"),
		Servers:  buildServerDefinitions(),
	}

	var buf bytes.Buffer
	if err = tpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return writeProjectFile("nginx", "default.conf.template", buf.Bytes())
}

func renderApacheConfig() (string, error) {
	tpl, err := template.New("apache").Funcs(template.FuncMap{"join": strings.Join}).Parse(apacheTemplate)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err = tpl.Execute(&buf, buildServerDefinitions()); err != nil {
		return "", err
	}

	return writeProjectFile("apache", "vhost.conf", buf.Bytes())
}

func writeProjectFile(component, filename string, content []byte) (string, error) {
	dir := filepath.Join(Env.GetString("PWD"), ".dl", component)
	if err := utils.CreateDirectory(dir); err != nil {
		return "", err
	}

	path := filepath.Join(dir, filename)
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return "", err
	}

	return path, nil
}

func buildServerDefinitions() []virtualHost {
	baseRoot := strings.TrimSpace(Env.GetString("DOCUMENT_ROOT"))
	base := virtualHost{DocumentRoot: baseRoot, IsBitrix: utils.BitrixCheck(baseRoot)}

	primaryCandidates := uniqueNonEmpty([]string{
		Env.GetString("LOCAL_DOMAIN"),
		Env.GetString("NIP_DOMAIN"),
		Env.GetString("HOST_NAME"),
	})

	for _, candidate := range primaryCandidates {
		addName(&base, candidate)
	}

	extra := []*virtualHost{}
	index := map[string]int{}

	for _, mapping := range hostMappings {
		host := strings.TrimSpace(mapping.Host)
		root := strings.TrimSpace(mapping.DocumentRoot)
		if host == "" || root == "" {
			continue
		}

		if root == base.DocumentRoot {
			addName(&base, host)
			continue
		}

		position, ok := index[root]
		if !ok {
			index[root] = len(extra)
			extra = append(extra, &virtualHost{DocumentRoot: root, IsBitrix: utils.BitrixCheck(root)})
			position = len(extra) - 1
		}

		addName(extra[position], host)
	}

	hosts := []virtualHost{base}
	for _, item := range extra {
		if item.Primary == "" {
			continue
		}
		hosts = append(hosts, *item)
	}

	return hosts
}

func addName(host *virtualHost, name string) {
	if name == "" {
		return
	}
	if host.Primary == "" {
		host.Primary = name
		return
	}
	if host.Primary == name {
		return
	}
	for _, alias := range host.Aliases {
		if alias == name {
			return
		}
	}
	host.Aliases = append(host.Aliases, name)
}

func uniqueNonEmpty(values []string) []string {
	seen := map[string]struct{}{}
	result := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		result = append(result, trimmed)
	}
	return result
}

func parseHostMappings(raw string) []HostMapping {
	entries := splitMappingEntries(raw)
	seen := map[string]int{}
	result := make([]HostMapping, 0, len(entries))

	for _, entry := range entries {
		trimmed := strings.TrimSpace(entry)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		pair := strings.Split(trimmed, "=>")
		if len(pair) != 2 {
			pair = strings.SplitN(trimmed, "=", 2)
		}
		if len(pair) != 2 {
			logrus.Warnf("Invalid host mapping entry: %s", trimmed)
			continue
		}

		host := strings.Trim(strings.TrimSpace(pair[0]), "\"'")
		root := strings.Trim(strings.TrimSpace(pair[1]), "\"'")
		if host == "" || root == "" {
			continue
		}

		if idx, ok := seen[host]; ok {
			result[idx].DocumentRoot = root
			continue
		}

		seen[host] = len(result)
		result = append(result, HostMapping{Host: host, DocumentRoot: root})
	}

	return result
}

func splitMappingEntries(raw string) []string {
	return strings.FieldsFunc(raw, func(r rune) bool {
		switch r {
		case '\n', '\r', ',', ';':
			return true
		default:
			return false
		}
	})
}

func buildTraefikRule(mappings []HostMapping) string {
	var builder strings.Builder
	seen := map[string]struct{}{}

	for _, mapping := range mappings {
		host := strings.TrimSpace(mapping.Host)
		if host == "" {
			continue
		}
		if _, ok := seen[host]; ok {
			continue
		}
		seen[host] = struct{}{}
		builder.WriteString(" || Host(`")
		builder.WriteString(host)
		builder.WriteString("`)")
	}

	return builder.String()
}

func HostMappings() []HostMapping {
	result := make([]HostMapping, len(hostMappings))
	copy(result, hostMappings)
	return result
}

func AdditionalCertificateHosts() []string {
	names := make([]string, 0, len(hostMappings))
	seen := map[string]struct{}{}
	for _, mapping := range hostMappings {
		host := strings.TrimSpace(mapping.Host)
		if host == "" {
			continue
		}
		if _, ok := seen[host]; ok {
			continue
		}
		seen[host] = struct{}{}
		names = append(names, host)
	}
	return names
}

const nginxTemplate = `{{range .Servers}}
server {
    listen 80;
    listen 443;

    server_name {{.Primary}}{{if .Aliases}} {{join .Aliases " "}}{{end}};
    add_header Strict-Transport-Security "max-age=31536000" always;
    client_max_body_size 200M;

    charset utf-8;

    set $root_path {{.DocumentRoot}};
    root $root_path;

    location / {
        root $root_path;
        index index.php index.html;
        {{if .IsBitrix}}
        try_files $uri $uri/ /index.php?$args /bitrix/urlrewrite.php?$args /bitrix/routing_index.php?$args;
        {{else}}
        try_files $uri $uri/ /index.php?$args;
        {{end}}
    }

    location ~ \.php$ {
        fastcgi_pass {{$.HostName}}_php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
     }

    location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpeg|avi|zip|gz|bz2|rar|swf|ico|7z|doc|docx|map|ogg|otf|pdf|tff|tif|txt|wav|webp|woff|woff2|xls|xlsx|xml)$ {
        expires 365d;
        try_files $uri $uri/ 404 = @fallback;
    }

    location @fallback {
        return 302 https://{{$.HostName}}/$uri;
    }
}

{{end}}`

const apacheTemplate = `{{range .}}
<VirtualHost *:80>
    ServerName {{.Primary}}
    {{if .Aliases}}ServerAlias {{join .Aliases " "}}
    {{end}}
    DocumentRoot {{.DocumentRoot}}

    <Directory {{.DocumentRoot}}>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /var/log/apache2/error.log
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>

{{end}}`
